apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: front-end-ui
  namespace: hygieia
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: front-end-ui
    spec:
      containers:
      - name: front-end-ui
        image: 54.202.110.124:8123/hygieia_ui:latest
        resources:
          requests:
            cpu: 700m
            memory: 500Mi
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: nexusregistrykey2
