apiVersion: v1
kind: Service
metadata:
  name: front-end-ui
  labels:
    name: front-end-ui
  namespace: hygieia
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30056
  selector:
    name: front-end-ui
